Version: 3

## Application Settings
APPLICATION_SETTINGS: &APPLICATION_SETTINGS
  Application: booking
  Module: api

Blueprints:
  api-account:
    Region: us-east-1
    Template: ./templates/api-account.yaml
    StackPolicy: ALLOW_ALL
    Capabilities: [CAPABILITY_IAM, CAPABILITY_NAMED_IAM]
    Package: true
    Parameters:
      <<: *APPLICATION_SETTINGS

  api-base:
    Region: us-east-1
    Template: ./templates/api-base.yaml
    StackPolicy: ALLOW_ALL
    Capabilities: [CAPABILITY_IAM, CAPABILITY_NAMED_IAM]
    Package: true
    Parameters:
      <<: *APPLICATION_SETTINGS

  apigw-resource:
    Region: us-east-1
    Template: ./templates/api-resource.yaml
    StackPolicy: ALLOW_ALL
    Capabilities: [CAPABILITY_IAM, CAPABILITY_NAMED_IAM]
    Package: false
    Parameters:
      <<: *APPLICATION_SETTINGS

Stages:
  test:
    api-account:
      Extends: api-account
      StackName: api-account
      Parameters:
        Environment: test

    public-api:
      Extends: api-base
      StackName: public-api
      Parameters:
        Environment: test
        APIAccess: public
        RetentionInDays: 7

    private-api:
      Extends: api-base
      StackName: private-api
      Parameters:
        Environment: test
        APIAccess: private
        RetentionInDays: 7

    #--------------------------------------------------------------
    #---------------------- PUBLIC RESOURCES ----------------------
    #--------------------------------------------------------------
    api-resource-hotels:
      Extends: apigw-resource
      StackName: api-resource-hotels
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/"
        MicroserviceResourceName: "hotels"
        IsResourcePathParameter: false

    api-resource-hotels-rooms:
      Extends: apigw-resource
      StackName: api-resource-hotel-rooms
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/hotels"
        MicroserviceResourceName: "rooms"
        IsResourcePathParameter: false

    api-resource-hotels-rooms-room-id:
      Extends: apigw-resource
      StackName: api-resource-hotel-rooms-room-id
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/hotels/rooms"
        MicroserviceResourceName: "room_id"
        IsResourcePathParameter: true

    api-resource-hotels-rooms-room-id-availability:
      Extends: apigw-resource
      StackName: api-resource-hotel-rooms-room-id-availability
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/hotels/rooms/room_id"
        MicroserviceResourceName: "availability"
        IsResourcePathParameter: false

    api-resource-reservations:
      Extends: apigw-resource
      StackName: api-resource-reservations
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/"
        MicroserviceResourceName: "reservations"
        IsResourcePathParameter: false

    api-resource-reservations-reservation-id:
      Extends: apigw-resource
      StackName: api-resource-reservations-reservation-id
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/reservations"
        MicroserviceResourceName: "reservation_id"
        IsResourcePathParameter: true

    api-resource-reservations-reservation-id-cancel:
      Extends: apigw-resource
      StackName: api-resource-reservations-reservation-id-cancel
      Parameters:
        Environment: test
        APIAccess: public
        MicroserviceParentPath: "/reservations/reservation_id"
        MicroserviceResourceName: "cancel"
        IsResourcePathParameter: false

    #--------------------------------------------------------------
    #---------------------- ADMIN RESOURCES ----------------------
    #--------------------------------------------------------------

    api-resource-admin-reservations:
      Extends: apigw-resource
      StackName: api-resource-admin-reservations
      Parameters:
        Environment: test
        APIAccess: private
        MicroserviceParentPath: "/"
        MicroserviceResourceName: "reservations"
        IsResourcePathParameter: false
