AWSTemplateFormatVersion: "2010-09-09"
Description: "API GW: Public API"

Parameters:
  Application:
    Type: String
  Module:
    Type: String
  Environment:
    Type: String
    AllowedValues: [dev, test, stg, prod]

  RetentionInDays:
    Description: Cloudwatch Logs retention in days
    Type: String
    Default: ""

Resources:
  API:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./api-base.yaml"
      Parameters:
        Application: !Ref Application
        Module: !Ref Module
        Environment: !Ref Environment
        RetentionInDays: !Ref RetentionInDays
        APIAccess: "public"

  #--------------------------------------------------------
  #---------------------- AUTHORIZER ----------------------
  #--------------------------------------------------------
  Authorizers:
    DependsOn: API
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateURL: "./api-authorizer.yaml"
      Parameters:
        Application: !Ref Application
        Module: !Ref Module
        Environment: !Ref Environment
        APIAccess: "public"
